export interface IMedicine {
    id: number,
    photo: string,
    med: string,
    type: boolean,
    kol: string,
}
export const arr = [
    {
        id: 1,
        photo: '/styles/medPhoto.webp',
        med: 'Стрепсилс',
        type: true,
        kol: "12",
    },
    {
        id: 2,
        photo: '/styles/medPhoto.webp',
        med: 'Кокаин',
        type: false,
        kol: "-",
    },
    {
        id: 3,
        photo: '/styles/medPhoto.webp',
        med: 'Героин',
        type: true,
        kol: "12",
    },
    {
        id: 4,
        photo: '/styles/medPhoto.webp',
        med: 'Амфетамин',
        type: false,
        kol: "-",
    },
    {
        id: 5,
        photo: '/styles/medPhoto.webp',
        med: 'Крокодил',
        type: true,
        kol: "12",
    },
    {
        id: 6,
        photo: '/styles/medPhoto.webp',
        med: 'Лизобакт',
        type: true,
        kol: '12',
    },
    {
        id: 7,
        photo: '/styles/medPhoto.webp',
        med: 'Стрепсилс',
        type: false,
        kol: '-',
    },
    {
        id: 8,
        photo: '/styles/medPhoto.webp',
        med: 'Лизорыт',
        type: true,
        kol: '12',
    },
    {
        id: 9,
        photo: '/styles/medPhoto.webp',
        med: 'Амнезия',
        type: false,
        kol: '-',
    },
]
